name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy to EC2 (AWS Linux 2)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ec2-user # AWS Linux 2 uses "ec2-user" instead of "ubuntu"
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/ec2-user/fastapi-book-project

            # Pull the latest code
            git pull origin main

            # Install Python dependencies
            pip3 install -r requirements.txt

            # Restart Gunicorn (already set up as a service)
            sudo systemctl restart fastapi

            # Copy Nginx configuration
            sudo cp nginx/nginx.conf /etc/nginx/conf.d/default.conf

            # Test and reload Nginx
            sudo nginx -t
            sudo systemctl reload nginx
